FROM ubuntu AS build

ARG LIBN00B_REPO=/n00b

WORKDIR $LIBN00B_REPO
COPY ./ $LIBN00B_REPO

# llvm.sh needs tools to install clang-18
RUN apt-get update && apt upgrade
RUN apt-get install -y \
    lsb-release \
    wget \
    software-properties-common \
    gnupg

RUN wget https://apt.llvm.org/llvm.sh
RUN chmod u+x llvm.sh
RUN ./llvm.sh 18

# meson install + crypto
RUN apt-get install -y \
    meson \
    libssl-dev

# ------
FROM build AS test

WORKDIR $LIBN00B_REPO
ENV TERM=dumb
RUN CC="clang-18" ./dev build

ENTRYPOINT [ "./dev", "run" ]
