name: tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - include/**
      - src/**
      - tests/**
      - meson.*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04

    if: |
      (
        github.event_name == 'pull_request' &&
        !contains(github.event.pull_request.body, format('skip:{0}', github.workflow))
      ) || (
        github.event_name == 'push'
      ) || (
        github.event_name == 'workflow_dispatch'
      )

    concurrency:
      # only allow one job per PR running
      # older pending jobs will be cancelled not to waste CI minutes
      # cannot use github.job here https://github.com/community/community/discussions/13496
      group: ${{ github.workflow }}-tests-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # 4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # 3.3.0
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # 3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Bake Images
        run: |
          docker buildx bake n00b --load

      - name: Compile N00b
        run: |
          docker compose run --rm n00b ./dev build

      - name: Run tests
        run: |
          echo TODO
